# 1. Import Cleaned data

In [1]:
import pandas as pd

df = pd.read_csv("/Users/kaviraj/Desktop/GUVI/Project3/cleaned_data.csv")

df

,specialty,appointment_time,gender,no_show,disability,place,appointment_shift,age,under_12_years_old,over_60_years_old,...,storm_day_before,rain_intensity,heat_intensity,appointment_date_continuous,Hipertension,Diabetes,Alcoholism,Handcap,Scholarship,SMS_received
0,psychotherapy,17,F,yes,intellectual,Lake Marvinville,afternoon,9.0,1,0,...,1,no_rain,warm,2020-01-01,0,0,0,0,0,0
1,Unknown,7,M,no,intellectual,ITAPEMA,morning,11.0,1,0,...,1,no_rain,cold,2020-01-01,0,0,0,0,0,0
2,speech therapy,16,M,no,intellectual,ITAJAÍ,afternoon,8.0,1,0,...,1,no_rain,warm,2020-01-01,0,0,0,0,0,0
3,speech therapy,14,M,yes,intellectual,Sarahside,afternoon,9.0,1,0,...,1,moderate,mild,2020-01-01,0,0,0,0,0,1
4,physiotherapy,8,M,no,motor,ITAJAÍ,morning,12.0,0,0,...,1,no_rain,mild,2020-01-01,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109552,psychotherapy,16,M,yes,intellectual,Unknown,afternoon,18.0,0,0,...,1,no_rain,mild,2021-05-11,0,0,0,0,0,0
109553,speech therapy,9,F,yes,motor,Port Georgestad,morning,18.0,0,0,...,1,moderate,warm,2021-05-11,0,0,0,0,0,0
109554,psychotherapy,13,F,no,intellectual,Erinton,afternoon,8.0,1,0,...,1,moderate,mild,2021-05-11,0,0,0,0,0,1
109555,physiotherapy,8,F,no,motor,CAMBORIU,morning,7.0,1,0,...,1,no_rain,warm,2021-05-11,0,0,0,0,0,0
109556,psychotherapy,11,M,no,Unknown,Unknown,morning,12.0,0,0,...,1,weak,cold,2021-05-12,0,0,0,0,0,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109557 entries, 0 to 109556
Data columns (total 27 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   specialty                    109557 non-null  object
 1   appointment_time             109557 non-null  int64
 2   gender                       109557 non-null  object
 3   no_show                      109557 non-null  object
 4   disability                   109557 non-null  object
 5   place                        109557 non-null  object
 6   appointment_shift            109557 non-null  object
 7   age                          109557 non-null  float64
 8   under_12_years_old           109557 non-null  int64
 9   over_60_years_old            109557 non-null  int64
 10  patient_needs_companion      109557 non-null  int64
 11  average_temp_day             109557 non-null  float64
 12  average_rain_day             109557 non-null  float64
 13  max_temp_day                 109557 non-null  float64
 14  max_rain_day                 109557 non-null  float64
 15  rainy_day_before             109557 non-null  int64
 16  storm_day_before             109557 non-null  int64
 17  rain_intensity               109557 non-null  object
 18  heat_intensity               109557 non-null  object
 19  appointment_date_continuous  109557 non-null  datetime64[ns]
 20  Hipertension                 109557 non-null  int64
 21  Diabetes                     109557 non-null  int64
 22  Alcoholism                   109557 non-null  int64
 23  Handcap                      109557 non-null  int64
 24  Scholarship                  109557 non-null  int64
 25  SMS_received                 109557 non-null  int64
 26  day_of_week                  109557 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(12), object(9)
memory usage: 22.6+ MB

# 2. Feature Engineering

In [2]:
# Change dtype of appoitment_date_continuous from object to datetime
df['appointment_date_continuous'] = pd.to_datetime(df['appointment_date_continuous'])

# creating new column day_of_week w.r.t date
df['day_of_week'] = df['appointment_date_continuous'].dt.day_name()
df.head(5)

,specialty,appointment_time,gender,no_show,disability,place,appointment_shift,age,under_12_years_old,over_60_years_old,...,rain_intensity,heat_intensity,appointment_date_continuous,Hipertension,Diabetes,Alcoholism,Handcap,Scholarship,SMS_received,day_of_week
0,psychotherapy,17,F,yes,intellectual,Lake Marvinville,afternoon,9.0,1,0,...,no_rain,warm,2020-01-01,0,0,0,0,0,0,Wednesday
1,Unknown,7,M,no,intellectual,ITAPEMA,morning,11.0,1,0,...,no_rain,cold,2020-01-01,0,0,0,0,0,0,Wednesday
2,speech therapy,16,M,no,intellectual,ITAJAÍ,afternoon,8.0,1,0,...,no_rain,warm,2020-01-01,0,0,0,0,0,0,Wednesday
3,speech therapy,14,M,yes,intellectual,Sarahside,afternoon,9.0,1,0,...,moderate,mild,2020-01-01,0,0,0,0,0,1,Wednesday
4,physiotherapy,8,M,no,motor,ITAJAÍ,morning,12.0,0,0,...,no_rain,mild,2020-01-01,0,0,0,0,0,0,Wednesday

# 3. Save Featured data as csv file

In [8]:
df.to_csv("c_featured_data.csv", index=False)