In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/kaviraj/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/kaviraj/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/kaviraj/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: numpy>=1.22.4 in /Users/kaviraj/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/kaviraj/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

# 1. Data Loading

In [2]:
import pandas as pd

df = pd.read_csv("/Users/kaviraj/Desktop/GUVI/Project3/Medical_appointment_data.csv")

df

,specialty,appointment_time,gender,no_show,disability,place,appointment_shift,age,under_12_years_old,over_60_years_old,...,storm_day_before,rain_intensity,heat_intensity,appointment_date_continuous,Hipertension,Diabetes,Alcoholism,Handcap,Scholarship,SMS_received
0,psychotherapy,17,F,yes,intellectual,Lake Marvinville,afternoon,9.0,1,0,...,1,no_rain,warm,2020-01-01,0,0,0,0,0,0
1,NaN,7,M,no,intellectual,ITAPEMA,morning,11.0,1,0,...,1,no_rain,cold,2020-01-01,0,0,0,0,0,0
2,speech therapy,16,M,no,intellectual,ITAJAÍ,afternoon,8.0,1,0,...,1,no_rain,warm,2020-01-01,0,0,0,0,0,0
3,speech therapy,14,M,yes,intellectual,Sarahside,afternoon,9.0,1,0,...,1,moderate,mild,2020-01-01,0,0,0,0,0,1
4,physiotherapy,8,M,no,motor,ITAJAÍ,morning,NaN,0,0,...,1,no_rain,mild,2020-01-01,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109588,psychotherapy,16,M,yes,intellectual,NaN,afternoon,18.0,0,0,...,1,no_rain,mild,2021-05-11,0,0,0,0,0,0
109589,speech therapy,9,F,yes,motor,Port Georgestad,morning,18.0,0,0,...,1,moderate,warm,2021-05-11,0,0,0,0,0,0
109590,psychotherapy,13,F,no,intellectual,Erinton,afternoon,8.0,1,0,...,1,moderate,mild,2021-05-11,0,0,0,0,0,1
109591,physiotherapy,8,F,no,motor,CAMBORIU,morning,7.0,1,0,...,1,no_rain,warm,2021-05-11,0,0,0,0,0,0
109592,psychotherapy,11,M,no,NaN,NaN,morning,NaN,0,0,...,1,weak,cold,2021-05-12,0,0,0,0,0,0

# 2. Understanding Data

In [78]:
df.shape

# (columns, rows)

(109593, 26)

In [ ]:
df.describe()

In [ ]:
df.isnull().sum()

In [ ]:
df.info()

# 3. Check Datatypes

In [3]:
df['appointment_date_continuous'] = pd.to_datetime(df['appointment_date_continuous'])

In [ ]:
df.info()

# 4. Handling missing values

specialty                      20127
appointment_time                   0
gender                             0
no_show                            0
disability                     16601
place                          11539
appointment_shift                  0
age                            22960
under_12_years_old                 0
over_60_years_old                  0
patient_needs_companion            0
average_temp_day                2211
average_rain_day                2245
max_temp_day                    2227
max_rain_day                    2263
rainy_day_before                   0
storm_day_before                   0
rain_intensity                     0
heat_intensity                     0
appointment_date_continuous        0
Hipertension                       0
Diabetes                           0
Alcoholism                         0
Handcap                            0
Scholarship                        0
SMS_received                       0

In [ ]:
# Missing percentage

df.isnull().sum()/len(df)*100

In [4]:
# Handling missing values for categorial data
# speciality, disability, place
# Unknown

df['specialty'] = df['specialty'].fillna('Unknown')
df['disability'] = df['disability'].fillna('Unknown')
df['place'] = df['place'].fillna('Unknown')

In [5]:
# Handling missing values for numerical data
# age, average_temp_day, average_rain_day, max_temp_day, max_rain_day
# median

missing_cols = ['age', 'average_temp_day', 'average_rain_day', 'max_temp_day', 'max_rain_day']

for col in missing_cols:
    df[col] = df[col].fillna(df[col].median())

In [6]:
df.isnull().sum()

specialty                      0
appointment_time               0
gender                         0
no_show                        0
disability                     0
place                          0
appointment_shift              0
age                            0
under_12_years_old             0
over_60_years_old              0
patient_needs_companion        0
average_temp_day               0
average_rain_day               0
max_temp_day                   0
max_rain_day                   0
rainy_day_before               0
storm_day_before               0
rain_intensity                 0
heat_intensity                 0
appointment_date_continuous    0
Hipertension                   0
Diabetes                       0
Alcoholism                     0
Handcap                        0
Scholarship                    0
SMS_received                   0
dtype: int64

In [30]:
df.describe()

,appointment_time,age,under_12_years_old,over_60_years_old,patient_needs_companion,average_temp_day,average_rain_day,max_temp_day,max_rain_day,rainy_day_before,storm_day_before,appointment_date_continuous,Hipertension,Diabetes,Alcoholism,Handcap,Scholarship,SMS_received
count,109593.000000,109593.000000,109593.000000,109593.000000,109593.000000,109593.000000,109593.000000,109593.000000,109593.000000,109593.000000,109593.000000,109593,109593.000000,109593.000000,109593.000000,109593.000000,109593.000000,109593.000000
mean,12.120966,17.242689,0.446424,0.071328,0.519823,20.351753,0.179982,24.030209,2.009931,0.937396,0.937533,2020-08-17 17:27:56.570584064,0.058088,0.023952,0.018541,0.009116,0.055113,0.311808
min,7.000000,2.000000,0.000000,0.000000,0.000000,8.940000,0.000000,13.300000,0.000000,0.000000,0.000000,2020-01-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9.000000,9.000000,0.000000,0.000000,0.000000,18.160000,0.000000,21.500000,0.000000,1.000000,1.000000,2020-04-19 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,13.000000,12.000000,0.000000,0.000000,1.000000,20.600000,0.010000,23.900000,0.200000,1.000000,1.000000,2020-07-28 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,15.000000,18.000000,1.000000,0.000000,1.000000,22.650000,0.150000,26.700000,1.800000,1.000000,1.000000,2021-01-06 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,18.000000,110.000000,1.000000,1.000000,1.000000,28.010000,4.770000,35.400000,45.000000,1.000000,1.000000,2021-05-12 00:00:00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
std,3.281623,15.937888,0.497124,0.257372,0.499609,3.411326,0.412714,3.919303,4.315088,0.242251,0.242004,NaN,0.233910,0.152901,0.134899,0.095040,0.228202,0.463234

# 5. Standardize Text Columns

In [83]:
columns = ['specialty',
 'appointment_time',
 'gender',
 'no_show',
 'disability',
 'place',
 'appointment_shift',
 'age',
 'under_12_years_old',
 'over_60_years_old',
 'patient_needs_companion',
 'average_temp_day',
 'average_rain_day',
 'max_temp_day',
 'max_rain_day',
 'rainy_day_before',
 'storm_day_before',
 'rain_intensity',
 'heat_intensity',
 'appointment_date_continuous',
 'Hipertension',
 'Diabetes',
 'Alcoholism',
 'Handcap',
 'Scholarship',
 'SMS_received']

for col in columns:
    print(f"\n{col}:")
    print(df[col].unique())

specialty:
['psychotherapy' 'Unknown' 'speech therapy' 'physiotherapy'
 'occupational therapy' 'assist' 'pedagogo' 'enf' 'sem especialidade']

appointment_time:
[17  7 16 14  8 13 10  9 11 15 18 12]

gender:
['F' 'M' 'I']

no_show:
['yes' 'no']

disability:
['intellectual' 'motor' 'Unknown' ' ']

place:
['Lake Marvinville' 'ITAPEMA' 'ITAJAÍ' ... 'West Gregoryport'
 'Reynoldsville' 'Wilcoxstad']

appointment_shift:
['afternoon' 'morning']

age:
[  9.  11.   8.  12.   7.  18.  14.   6.  13.  10.  15.  19.  59.  62.
   4.  28.  60.  61.  17.  21.  68.  16.  57.  67.   5.  20.  55.  63.
  77.  42.  69.  26.  87.  45.  46.  70.  23.  25.  43.  38.  88.  50.
  40.  64.  58.  31.  37.  52.  65.  51.  91.  73.  39.  72.  49.  81.
  22.  66.  27.  44.  53.  75.  30.  35.  24.  48.  82.  54.  78.  84.
  47.  80.  41.  29.  32.   3.  56.  34.  74.  83.  86.  79. 110. 106.
  36.   2. 108.  33.  76.  71.  85.  89.]

under_12_years_old:
[1 0]

over_60_years_old:
[0 1]

patient_needs_companion:
[1 0]

average_temp_day:
[23.18 14.31 21.61 ... 11.35 11.47 13.18]

average_rain_day:
[0.   0.02 0.01 0.11 0.19 0.32 0.36 0.29 0.2  0.14 0.47 0.52 0.18 0.03
 0.08 0.15 0.22 0.23 0.73 0.17 0.34 0.04 1.69 0.12 1.8  0.91 0.16 0.1
 0.05 0.09 2.45 1.26 0.37 0.72 0.49 1.73 0.13 0.55 0.35 0.31 1.25 0.69
 0.81 0.41 0.28 0.98 0.66 0.33 2.27 0.27 1.11 0.59 3.44 0.82 0.21 0.4
 0.48 0.6  0.06 0.7  0.26 1.   1.48 1.61 0.53 0.67 2.11 0.56 0.77 1.87
 0.65 1.12 0.07 0.78 0.87 1.4  1.3  1.43 0.71 0.3  1.96 0.68 0.25 0.84
 1.04 2.36 2.21 0.39 2.33 0.74 0.88 1.08 2.38 1.42 2.37 1.36 0.43 2.26
 0.24 2.22 0.83 0.42 0.63 1.39 1.47 0.75 1.02 0.38 1.24 0.79 2.39 1.2
 0.44 2.87 0.45 1.51 2.32 1.15 2.15 0.89 0.5  1.6  1.56 1.62 0.62 0.96
 0.97 1.09 0.85 0.64 2.19 1.37 1.23 1.65 1.27 1.19 2.42 1.38 1.34 0.76
 2.2  1.45 2.16 0.61 1.03 2.46 2.31 1.68 2.29 1.44 0.46 0.92 0.51 4.22
 0.57 1.85 1.54 2.3  0.8  1.01 1.22 1.53 2.25 2.24 1.05 1.07 1.41 1.35
 2.05 1.59 1.57 2.18 1.78 1.55 1.63 0.99 1.13 1.52 4.77 2.28 1.14 0.93
 2.17 2.12 2.92 0.54 1.49 1.31 1.33 1.95 1.17 0.58 2.34 1.67 1.06 1.18
 2.47 0.94 1.1  1.32 2.23 2.35 0.95 1.71 3.25 1.21 1.28 1.16 2.4  1.82
 1.76 2.59 1.5  2.1  2.03 2.07 1.29 1.79 1.74 1.81 1.46 1.58 2.09 0.9
 1.94 1.64 0.86 1.83 1.84 2.13 2.57 2.14 2.   1.75 2.44 2.49 1.66 2.01
 2.43 2.56 2.06 1.77 1.7  2.41 1.89 2.51 1.99 1.72 1.97 1.86 1.9  1.92
 2.04 2.54 2.08 2.5  1.98 2.02 2.48 1.91 1.93 2.58]

max_temp_day:
[27.5 16.5 29.9 24.1 23.1 20.8 24.6 26.1 19.8 19.1 27.4 33.5 21.2 29.7
 22.4 22.9 28.3 22.5 25.1 28.8 22.1 30.9 24.7 27.6 24.9 30.6 16.7 24.2
 19.5 24.4 23.9 21.  17.3 25.2 25.6 25.3 22.7 23.7 28.9 27.9 25.8 17.1
 22.8 31.1 29.2 26.3 26.6 18.5 27.2 24.5 29.8 25.4 22.  23.8 20.9 27.3
 23.  30.3 25.7 17.7 19.6 17.2 27.1 21.7 24.3 24.  21.4 21.6 25.  26.4
 29.  22.2 26.5 31.3 28.4 20.7 21.8 29.6 22.3 15.3 26.2 21.5 29.3 17.8
 24.8 20.5 28.  22.6 31.7 32.  32.9 26.9 29.1 23.6 23.3 33.9 33.8 25.5
 18.1 20.3 27.8 16.  28.1 30.2 27.7 15.6 25.9 20.  16.3 19.  30.4 28.7
 20.4 16.6 16.8 23.2 17.  31.2 18.4 21.9 20.1 19.7 29.5 26.8 15.5 17.4
 14.2 14.8 15.  35.  34.3 14.  15.4 16.1 18.  20.6 18.3 28.5 18.6 34.5
 21.1 15.9 26.7 31.5 29.4 30.5 19.3 17.6 23.5 35.4 19.2 34.7 19.4 31.8
 13.3 30.  18.2 31.9 34.  21.3 30.1 14.6 23.4 18.9 28.2 19.9 18.8 16.2
 26.  13.8 17.5 30.7 16.4 31.  14.7 17.9 34.2 16.9 14.9 15.7 34.1 33.2
 34.4 33.7 28.6 14.3 14.1 31.6 33.1 20.2 31.4 30.8 18.7 13.9 33.  27.
 15.1 13.5 33.4 33.3 14.4 13.4 32.1 33.6 13.6 15.2 34.8 15.8 32.8 34.6
 14.5 34.9 32.5 35.1 32.6 13.7 32.3 35.3 32.7 35.2 32.4 32.2]

max_rain_day:
[ 0.   0.6  0.2  1.4  3.2  0.1  4.   0.5  3.6  9.7  0.4  3.  15.   0.3
  3.8  2.6  1.3  3.1  3.5  1.8  3.4  8.2  5.6  2.1 10.  19.8  2.   3.3
  3.7 12.4  1.7  8.9  1.6  1.9  0.8 25.9 25.7 21.2  7.8 22.2  8.6  2.3
  4.2  6.2  1.   6.4 15.8 18.6  5.2  6.3  7.   8.5 16.7 12.6 16.4  3.9
 26.6  0.9  0.7 16.2  1.1 17.6  1.5  1.2  2.8  4.8  2.9 28.4  8.   4.6
 17.  11.8  6.6  2.5 29.4  2.4  9.6  6.5 18.5  2.2 19.   8.1 11.2 18.7
 17.2 10.5  5.9  6.   9.8  6.1 12.8  7.4 11.7  5.1 11.9 12.1 13.6  7.2
 10.7  9.9  4.1 14.5 28.  28.3  6.8 15.1  4.9  4.5 10.2  5.8 15.9  9.4
  9.1 10.4  5.4 21.6  4.4 10.8 16.3  9.  18.2 16.8 11.5  4.3 13.8  8.3
  5.  18.8 19.2 17.8  7.6 14.4 14.6 23.6  5.5 12.9 11.1  9.2 15.2 24.4
  5.7 18.9 10.1 23.2  7.7 12.2 11.   2.7 16.   6.7 10.9 11.6 11.4 12.
 18.4  9.3 32.8 13.3 24.6 14.3 21.1 26.9 13.2  9.5 13.4  7.5 19.3 10.6
 13.   8.4 14.  17.4 17.5 15.4 16.1 26.7  6.9 23.3  5.3 24.2  7.9  8.8
 16.6 24.9 27.  22.3 30.9 22.1 28.9 43.4 45.  17.1 29.1 14.1 12.5 13.7
 14.2 19.4 11.3 20.1 18.1 24.8 12.3 14.8 19.5 15.7 26.  16.9 14.9 16.5
 23.8 26.1  8.7 26.8 23.1 27.4 15.5 26.2 10.3 27.8 21.3 12.7  7.1 28.5
 28.1 31.7 13.5 25.  23.  30.1 20.4 22.8 31.6  4.7 17.9 27.7 13.9 15.6
 20.  13.1 25.8 27.5 17.7 24.  20.2 18.  17.3 19.9 20.7 31.8 15.3 30.
 23.7 18.3 22.9 25.4 29.7 19.6 14.7 20.3 25.2 30.2 25.1 28.6 28.7 19.1
 20.5 30.5 25.3  7.3 22.  28.2 29.9 27.9 22.6 29.  24.7 22.4 19.7 29.2
 20.6 24.5 30.3 27.1 24.1 26.3 20.8 27.2 23.5 23.9 27.3 29.8 26.4 20.9
 26.5 27.6 28.8 21.4 22.5 21.5 29.6 29.3 23.4 24.3 25.5 22.7 31.1 21.9
 21.  32.4 33.1 29.5 33.  31.  30.8 30.7 21.8 31.2 30.6 31.9 25.6 30.4
 32.2 31.4 31.3 31.5]

rainy_day_before:
[1 0]

storm_day_before:
[1 0]

rain_intensity:
['no_rain' 'moderate' 'weak' 'heavy']

heat_intensity:
['warm' 'cold' 'mild' 'heavy_warm' 'heavy_cold']

appointment_date_continuous:
<DatetimeArray>
['2020-01-01 00:00:00', '2020-01-02 00:00:00', '2020-01-03 00:00:00',
 '2020-01-04 00:00:00', '2020-01-05 00:00:00', '2020-01-06 00:00:00',
 '2020-01-07 00:00:00', '2020-01-08 00:00:00', '2020-01-09 00:00:00',
 '2020-01-10 00:00:00',
 ...
 '2021-05-03 00:00:00', '2021-05-04 00:00:00', '2021-05-05 00:00:00',
 '2021-05-06 00:00:00', '2021-05-07 00:00:00', '2021-05-08 00:00:00',
 '2021-05-09 00:00:00', '2021-05-10 00:00:00', '2021-05-11 00:00:00',
 '2021-05-12 00:00:00']
Length: 498, dtype: datetime64[ns]

Hipertension:
[0 1]

Diabetes:
[0 1]

Alcoholism:
[0 1]

Handcap:
[0 1]

Scholarship:
[0 1]

SMS_received:
[0 1]

In [7]:
df['disability'] = df['disability'].str.strip()
df['disability'] = df['disability'].replace('', 'Unknown')

In [7]:
df['disability'].unique()

array(['intellectual', 'motor', 'Unknown'], dtype=object)

# 6. Duplicates

In [54]:
df.duplicated().sum()

np.int64(36)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.shape

(109557, 26)

# 7. Save cleaned dataset

In [10]:
df.to_csv("cleaned_data.csv", index=False)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 109557 entries, 0 to 109592
Data columns (total 26 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   specialty                    109557 non-null  object
 1   appointment_time             109557 non-null  int64
 2   gender                       109557 non-null  object
 3   no_show                      109557 non-null  object
 4   disability                   109557 non-null  object
 5   place                        109557 non-null  object
 6   appointment_shift            109557 non-null  object
 7   age                          109557 non-null  float64
 8   under_12_years_old           109557 non-null  int64
 9   over_60_years_old            109557 non-null  int64
 10  patient_needs_companion      109557 non-null  int64
 11  average_temp_day             109557 non-null  float64
 12  average_rain_day             109557 non-null  float64
 13  max_temp_day                 109557 non-null  float64
 14  max_rain_day                 109557 non-null  float64
 15  rainy_day_before             109557 non-null  int64
 16  storm_day_before             109557 non-null  int64
 17  rain_intensity               109557 non-null  object
 18  heat_intensity               109557 non-null  object
 19  appointment_date_continuous  109557 non-null  datetime64[ns]
 20  Hipertension                 109557 non-null  int64
 21  Diabetes                     109557 non-null  int64
 22  Alcoholism                   109557 non-null  int64
 23  Handcap                      109557 non-null  int64
 24  Scholarship                  109557 non-null  int64
 25  SMS_received                 109557 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(12), object(8)
memory usage: 22.6+ MB